FROM docker.elastic.co/beats/filebeat-oss:7.12.1
USER root
RUN yum clean all && yum update -y \ 
    && yum install -y make gcc perl-core pcre-devel wget zlib-devel \
    && yum clean all
RUN wget https://ftp.openssl.org/source/openssl-1.1.1w.tar.gz && tar -xzvf openssl-1.1.1w.tar.gz && cd openssl-1.1.1w \
    && ./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic  && make && make install
